using Editors.Audio.Shared.Wwise.Engine.Dsp;
using NAudio.CoreAudioApi;
using NAudio.Wave;
using NAudio.Wave.SampleProviders;

namespace Editors.Audio.Shared.Wwise.Engine.Output
{
    internal interface IAudioOutputDevice : IDisposable
    {
        bool EnsureCreated(ISampleProvider audioSampleSource);

        // True only when a stopped device actually had to be started, because that is when its
        // clock restarts from zero and the position epoch has to be re-anchored to it.
        bool EnsurePlaying();
        AudioDevicePosition? CaptureOutputPosition();
    }

    internal sealed class AudioOutputDevice : IAudioOutputDevice
    {
        // How much audio the sink holds ahead of what is being heard, which is also how long
        // playback runs on after a pause.
        private const int OutputLatencyMilliseconds = 20;

        // Generous for real device changes -- a session might see a handful -- and far below the
        // rate a stuck trigger produces.
        private const int MaximumRebuilds = 32;

        private readonly object _outputPlayerLock = new();
        private readonly ILogger _logger = Logging.Create<AudioOutputDevice>();
        private IWavePlayer _outputPlayer;

        // Kept so the sink can be rebuilt on the endpoint the machine has moved to. The engine hands
        // this over once and has no idea the device underneath it ever changed.
        private ISampleProvider _audioSampleSource;

        // Windows can take the endpoint away underneath a running sink -- the default output
        // changes, headphones are unplugged, a driver restarts. Watching for it is what turns "the
        // sound stopped and nobody knows why" into a device the engine can rebuild on.
        private MMDeviceEnumerator _deviceEnumerator;
        private EndpointChangeWatcher _endpointChangeWatcher;
        private volatile bool _isDisposed;

        // Set when the endpoint has gone and the sink has to be rebuilt before it can play again.
        private volatile bool _needsRebuild;

        // How many times the sink has been rebuilt on a new endpoint, and how many rebuilds failed.
        // Diagnostics: a device change is invisible from outside otherwise, and "did it come back"
        // is the whole question when one happens.
        internal int RebuildCount { get; private set; }
        internal int FailedRebuildCount { get; private set; }
        internal string LastEndpointChangeReason { get; private set; } = "none";

        // Which endpoint the sink was built on, so a notification about some other device can be
        // ignored. Windows moves several endpoints around while the default is being changed.
        private string _endpointIdInUse = string.Empty;

        public bool EnsureCreated(ISampleProvider audioSampleSource)
        {
            if (_outputPlayer != null)
                return false;

            lock (_outputPlayerLock)
            {
                if (_outputPlayer != null)
                    return false;

                _audioSampleSource = audioSampleSource;
                StartWatchingForEndpointChanges();
                LogDefaultOutputMixFormat(audioSampleSource.WaveFormat);

                _outputPlayer = CreateOutputPlayer(audioSampleSource);
                return true;
            }
        }

        // The one place the sink is built, so EnsureCreated and a rebuild after an endpoint change
        // cannot drift apart.
        //
        // WASAPI in shared mode, event synced, fed 16-bit PCM.
        //
        // The noise this engine was originally blamed for was the sink, and it was settled on
        // 2026-09-11: it is float output, and nothing of this project is involved in it. A bare sine
        // generated by a test -- no engine, no voice pool -- captured as it was handed to the sink
        // reads peak 255.0 against a generated 0.5, with 240,251 of 241,536 frames discontinuous,
        // every run. The same sine through the same sink as 16-bit is exact.
        //
        // What every earlier confusion turned on: Init(ISampleProvider) converts to 32-bit float,
        // Init(new SampleToWaveProvider16(...)) does not. **Do not replace the conversion below with
        // the ISampleProvider overload.** That is the fault.
        private IWavePlayer CreateOutputPlayer(ISampleProvider audioSampleSource)
        {
            // Resolved explicitly rather than letting WasapiOut pick, so the endpoint the sink is
            // built on is known and notifications about other devices can be ignored.
            using var enumerator = new MMDeviceEnumerator();
            var endpoint = enumerator.GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia);
            _endpointIdInUse = endpoint.ID;

            var outputPlayer = new WasapiOut(endpoint, AudioClientShareMode.Shared, true, OutputLatencyMilliseconds);
            outputPlayer.PlaybackStopped += OnPlaybackStopped;
            outputPlayer.Init(new SampleToWaveProvider16(audioSampleSource));

            // What the device accepted, as opposed to what it was offered. The two are allowed to
            // differ, and knowing which is which is the first thing anyone debugging the sink needs.
            _logger.Here().Information(
                $"Output device {outputPlayer.GetType().Name} accepted " +
                $"{outputPlayer.OutputWaveFormat.SampleRate} Hz, {outputPlayer.OutputWaveFormat.Channels} channels, " +
                $"{outputPlayer.OutputWaveFormat.BitsPerSample}-bit {outputPlayer.OutputWaveFormat.Encoding}");
            return outputPlayer;
        }

        public bool EnsurePlaying()
        {
            lock (_outputPlayerLock)
            {
                var wasRebuilt = RebuildIfNeeded();
                if (_outputPlayer == null)
                    return false;
                if (_outputPlayer.PlaybackState != PlaybackState.Stopped)
                    return wasRebuilt;

                _outputPlayer.Play();
                return true;
            }
        }

        // Recovery must not wait for the game to start something new.
        //
        // The position is read every twenty-five milliseconds by the completion poll for as long as
        // anything is playing, so checking here is what makes a device change recover on its own.
        // Hanging it off EnsurePlaying alone meant a sink stayed broken until something was posted,
        // which for a tone already playing is never.
        private bool RebuildIfNeeded()
        {
            if (!_needsRebuild || _isDisposed)
                return false;

            // Rebuilding in a loop is worse than not rebuilding at all -- it was measured at
            // twenty-five rebuilds in thirty seconds when the trigger was too broad, and the
            // playhead fell a second and a half behind wall clock. The trigger is narrow now, and
            // this is the backstop: a burst of them means something is still raising the flag, and
            // it should be reported rather than silently absorbed.
            if (RebuildCount >= MaximumRebuilds)
            {
                _needsRebuild = false;
                _logger.Here().Error(
                    $"The audio output device has been rebuilt {RebuildCount} times; refusing further rebuilds. " +
                    $"The last endpoint change seen was: {LastEndpointChangeReason}");
                return false;
            }

            return RebuildOnCurrentEndpoint();
        }

        // Rebuilds the sink on whatever endpoint the machine is using now.
        //
        // Returns true only if the rebuilt device actually started, because the caller uses that to
        // decide whether the position epoch has to be re-anchored -- and a rebuilt device is a new
        // clock starting at zero, which is exactly the case the epoch exists for.
        private bool RebuildOnCurrentEndpoint()
        {
            _needsRebuild = false;
            if (_audioSampleSource == null)
                return false;

            DisposeOutputPlayer();
            try
            {
                _outputPlayer = CreateOutputPlayer(_audioSampleSource);
                RebuildCount++;
                _logger.Here().Information("Audio output device rebuilt after the endpoint changed");
                return true;
            }
            catch (Exception exception)
            {
                // Nothing is left claiming to play. A sink that cannot be rebuilt is reported and
                // stays absent rather than being retried on every callback.
                _outputPlayer = null;
                FailedRebuildCount++;
                _logger.Here().Error(exception, "The audio output device could not be rebuilt; playback has stopped");
                return false;
            }
        }

        private void StartWatchingForEndpointChanges()
        {
            if (_endpointChangeWatcher != null)
                return;
            try
            {
                _deviceEnumerator = new MMDeviceEnumerator();
                _endpointChangeWatcher = new EndpointChangeWatcher(OnEndpointChanged, IsDeviceInUse);
                _deviceEnumerator.RegisterEndpointNotificationCallback(_endpointChangeWatcher);
            }
            catch (Exception exception)
            {
                // Not fatal: without the watcher a device change is heard as playback stopping,
                // which is what happened before there was one.
                _endpointChangeWatcher = null;
                _logger.Here().Warning(exception, "Could not watch for audio endpoint changes");
            }
        }

        private bool IsDeviceInUse(string deviceId)
            => string.Equals(deviceId, _endpointIdInUse, StringComparison.OrdinalIgnoreCase);

        // Called by Windows, on its own thread, so it does no more than raise the flag. Rebuilding
        // here would tear down a sink from inside a notification the driver is still holding.
        private void OnEndpointChanged(string reason)
        {
            if (_isDisposed)
                return;
            _needsRebuild = true;
            LastEndpointChangeReason = reason;
            _logger.Here().Information($"Audio endpoint changed ({reason}); the sink will be rebuilt on the next playback");
        }

        public AudioDevicePosition? CaptureOutputPosition()
        {
            lock (_outputPlayerLock)
            {
                if (RebuildIfNeeded())
                    _outputPlayer?.Play();
                if (_outputPlayer is not IWavePosition outputWavePosition)
                    return null;
                try
                {
                    var averageBytesPerSecond = outputWavePosition.OutputWaveFormat.AverageBytesPerSecond;
                    if (averageBytesPerSecond > 0)
                        return new AudioDevicePosition(outputWavePosition.GetPosition(), averageBytesPerSecond);
                    else
                        return null;
                }
                catch
                {
                    return null;
                }
            }
        }

        private void LogDefaultOutputMixFormat(WaveFormat mixerFormat)
        {
            try
            {
                using var deviceEnumerator = new MMDeviceEnumerator();
                using var outputEndpoint = deviceEnumerator.GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia);
                using var audioClient = outputEndpoint.AudioClient;
                var outputMixFormat = audioClient.MixFormat;
                var mixSubFormat = outputMixFormat is WaveFormatExtensible extensibleMixFormat
                    ? extensibleMixFormat.SubFormat.ToString()
                    : "not extensible";
                _logger.Here().Information($"Audio output endpoint subformat: {mixSubFormat}");
                _logger.Here().Information(
                    $"Audio output endpoint '{outputEndpoint.FriendlyName}' mixes at " +
                    $"{outputMixFormat.SampleRate} Hz, {outputMixFormat.Channels} channels, {outputMixFormat.BitsPerSample}-bit {outputMixFormat.Encoding}; " +
                    $"playback renders at {mixerFormat.SampleRate} Hz, {mixerFormat.Channels} channels, {mixerFormat.BitsPerSample}-bit {mixerFormat.Encoding}; " +
                    $"Windows sample rate conversion required {outputMixFormat.SampleRate != mixerFormat.SampleRate}");
            }
            catch (Exception exception)
            {
                _logger.Here().Warning(exception, "Could not query the default Windows output endpoint mix format");
            }
        }

        private void OnPlaybackStopped(object _, StoppedEventArgs eventArgs)
        {
            if (_isDisposed)
                return;

            // An exception here means the endpoint went away underneath the sink. Marking it for
            // rebuild is what makes that recoverable: before, the public state went on claiming
            // playback that no device was consuming.
            if (eventArgs.Exception != null)
            {
                _needsRebuild = true;
                _logger.Here().Error(eventArgs.Exception, "Audio output device stopped unexpectedly; the sink will be rebuilt on the next playback");
            }
            else
                _logger.Here().Warning(
                    "Audio output device stopped on its own. Nothing asks it to stop, so the sink ran out of " +
                    "audio to play, which is heard as a break in the sound rather than as silence");
        }

        private void DisposeOutputPlayer()
        {
            if (_outputPlayer == null)
                return;
            _outputPlayer.PlaybackStopped -= OnPlaybackStopped;
            _outputPlayer.Dispose();
            _outputPlayer = null;
        }

        // Stopping the player cuts whatever it is holding, so a voice still sounding is chopped
        // off at whatever level it reached -- heard as a click, and described by one listener as
        // "the sound of pulling a speaker out". The engine ramps its voices to silence before
        // getting here; this waits for that silence to actually reach the speakers, which takes as
        // long as the device holds audio ahead of what is being heard.
        public void Dispose()
        {
            _isDisposed = true;
            StopWatchingForEndpointChanges();
            lock (_outputPlayerLock)
            {
                if (_outputPlayer?.PlaybackState == PlaybackState.Playing)
                    Thread.Sleep(OutputLatencyMilliseconds + GainRamp.DeclickMilliseconds);
                _outputPlayer?.Stop();
                DisposeOutputPlayer();
            }
        }

        private void StopWatchingForEndpointChanges()
        {
            try
            {
                if (_endpointChangeWatcher != null)
                    _deviceEnumerator?.UnregisterEndpointNotificationCallback(_endpointChangeWatcher);
            }
            catch (Exception exception)
            {
                _logger.Here().Warning(exception, "Could not stop watching for audio endpoint changes");
            }
            finally
            {
                _endpointChangeWatcher = null;
                _deviceEnumerator?.Dispose();
                _deviceEnumerator = null;
            }
        }
    }
}
